# refer to the Common Application properties
# <https://docs.spring.io/spring-boot/docs/current/reference/html/appendix-application-properties.html#common-application-properties>
spring:
#  profiles:
#    active: dev
  application:
    name: JNDI TargetApp

server:
  port: 8080
  servlet:
    context-path: /jndi-targetapp
